name: bored
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter_dotenv: ^5.0.2
  google_fonts: ^2.2.0
  equatable: ^2.0.3
  flutter_svg: ^1.0.0
  dartz: ^0.10.1
  freezed_annotation:
  sentry_flutter: ^6.2.2
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3
  auto_route: ^3.2.1
  lottie: ^1.2.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  freezed: 
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/

